## Introduction to Numpy

#### **Name:** Jesus Ramos


#### Import numpy

In [1]:
import numpy as np

#### Numpy operations
1.- Create array a with values from 1-5 \
2.- create an array b with values from 6 - 10

In [2]:
arrA = np.array([1, 2, 3, 4, 5])

In [3]:
arrB = np.array([6, 7, 8, 9, 10])

#### Matrix Operations with numpy

1. Create a 3x3 matrix in numpy with the following values: 

⎡ 1  2  3 ⎤ \
⎢ 4  5  6 ⎥ \
⎣ 7  8  9 ⎦ 

2.- Transpose the matrix and save it into a transpose variable \
3.- Add both matrix \
4.- Multiply both matrix



In [4]:
m = np.matrix('1 2 3; 4 5 6; 7 8 9')
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
mt = m.getT()
mt

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [8]:
ms = np.add(m,mt)
ms

matrix([[ 2,  6, 10],
        [ 6, 10, 14],
        [10, 14, 18]])

In [9]:
mm = np.dot(mt, ms)
mm

matrix([[ 96, 144, 192],
        [114, 174, 234],
        [132, 204, 276]])

#### numpy indexing

1.- Create a numpy array [10, 20, 30, 40, 50, 60] \
2.- print second and last index \
3.- print elements 1-3 \
4.- print all but the first 2 elements \
5.- reshape the array to be a 2x3 matrix 

In [11]:
arr = np.linspace(10,60, 6, dtype=int)
arr

array([10, 20, 30, 40, 50, 60])

#### Creating random arrays
1- Create a 3x3 matrix with random numbers. \
2.- Create a 2x3 matrix with random integers.


#### Boolean Indexing and Filtering
1.- Generate a random dataset in a 5x5 matrixs filled with integers from 1-50. \
2.- Filter the values that are bigger than 25 and replace them with 0. \
3.- Calculate the basic statisticañ dispersion and tendency meassurements.

#### Homework exercise numpy

⎡ 2  3 ⎤ \
⎣ 0  1 ⎦ 


⎡ 1  2 ⎤  
⎣ 4  0 ⎦ 

1. The product
2. Product's transpose.
3. Determinant of the product
4. The inverse of the product.